# Generated by Django 5.2.7 on 2025-10-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billsOfLading', models.FileField(blank=True, null=True, upload_to='billsOfLading/')),
                ('customDocumentation', models.FileField(blank=True, null=True, upload_to='customDocumentation/')),
                ('exportDeclaration', models.FileField(blank=True, null=True, upload_to='exportDeclaration/')),
                ('shippingManifest', models.FileField(blank=True, null=True, upload_to='shippingManifest/')),
                ('vesselInformation', models.FileField(blank=True, null=True, upload_to='vesselInformation/')),
                ('sealContainerNumber', models.FileField(blank=True, null=True, upload_to='sealContainerNumber/')),
                ('diagram', models.FileField(blank=True, null=True, upload_to='diagrams/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Order Placed', max_length=50)),
                ('address', models.CharField(default='', max_length=100)),
                ('oilReqSent', models.BooleanField(default=False)),
                ('oilFilled', models.BooleanField(default=False)),
                ('customReqSent', models.BooleanField(default=False)),
                ('customTax', models.IntegerField(default=-1)),
                ('customTaxSent', models.BooleanField(default=False)),
                ('shipReqSent', models.BooleanField(default=False)),
                ('shippingCost', models.IntegerField(default=-1)),
                ('shippingCostSent', models.BooleanField(default=False)),
                ('shippingCostVerified', models.BooleanField(default=False)),
                ('tankerPicked', models.BooleanField(default=False)),
                ('tankerDropedAtPort', models.BooleanField(default=False)),
                ('customCleared', models.BooleanField(default=False)),
                ('tankerDispatched', models.BooleanField(default=False)),
                ('orderRecieved', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExcelSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tankPressure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('toGoMt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.order')),
            ],
        ),
    ]
